name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - integration
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"

jobs:
  test:
    name: Yarn Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ["^16"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          echo 'export default {};' >> src/aws-exports.js  # Dummy file
          yarn install --dev
          yarn test
          # yarn deploy
